/* Word parts are spelling tiles. Audio reads whole words, never isolated phonemes. */
const WORD_SETS = {
 familiar: [
 ['cat','c|a|t','A pet that purrs.'], ['dog','d|o|g','A pet that barks.'],
 ['fish','f|i|sh','An animal with fins that lives in water.'], ['ship','sh|i|p','A very large boat.'],
 ['shop','sh|o|p','A place where you buy things.'], ['chip','ch|i|p','A strip of potato you might eat with fish.'],
 ['chin','ch|i|n','The part of your face below your mouth.'], ['thin','th|i|n','The opposite of thick.'],
 ['king','k|i|ng','A man who rules a kingdom.'], ['ring','r|i|ng','Jewellery you wear on a finger.'],
 ['rain','r|ai|n','Water that falls from clouds.'], ['train','t|r|ai|n','It travels on rails.'],
 ['boat','b|oa|t','A small way to travel on water.'], ['coat','c|oa|t','Wear this over your clothes outside.'],
 ['feet','f|ee|t','You put your shoes on these.'], ['sleep','s|l|ee|p','You do this in bed at night.'],
 ['night','n|igh|t','The dark part of the day.'], ['light','l|igh|t','Switch this on to see in a dark room.'],
 ['park','p|ar|k','An outdoor place with grass and swings.'], ['farm','f|ar|m','A place where crops grow and animals are kept.'],
 ['fork','f|or|k','Use this with a knife to eat your dinner.'], ['short','sh|or|t','The opposite of tall.'],
 ['book','b|oo|k','Something with pages that you read.'], ['food','f|oo|d','What you eat when you are hungry.'],
 ['town','t|ow|n','A place with houses and shops, smaller than a city.'], ['coin','c|oi|n','A round piece of metal money.'],
 ['chair','ch|air','A seat with a back.'], ['splash','s|p|l|a|sh','The noise of jumping into water.'],
 ['spring','s|p|r|i|ng','The season after winter.'], ['crunch','c|r|u|n|ch','The noise of biting a crisp apple.']
 ],
 challenge: [
 ['dream','d|r|ea|m','A story in your head when you sleep.'], ['beach','b|ea|ch','Sand beside the sea.'],
 ['steam','s|t|ea|m','Hot water vapour rising from a kettle.'], ['cream','c|r|ea|m','Something thick and milky you can pour on a pudding.'],
 ['cloud','c|l|ou|d','A white or grey shape in the sky.'], ['shout','sh|ou|t','Say something very loudly.'],
 ['proud','p|r|ou|d','How you feel when you have done something really well.'], ['sound','s|ou|n|d','Something you can hear.'],
 ['chew','ch|ew','What your teeth do to food.'], ['grew','g|r|ew','The past tense of grow.'],
 ['screw','s|c|r|ew','Turn this metal fixing with a screwdriver.'], ['blew','b|l|ew','The past tense of blow.'],
 ['bright','b|r|igh|t','Full of light.'], ['flight','f|l|igh|t','A journey through the air.'],
 ['float','f|l|oa|t','Stay on top of the water.'], ['throat','th|r|oa|t','The part inside your neck where you swallow.'],
 ['coach','c|oa|ch','A person who trains a football team.'], ['three','th|r|ee','One more than two.'],
 ['green','g|r|ee|n','The colour of grass.'], ['street','s|t|r|ee|t','A road with buildings along it.'],
 ['spoon','s|p|oo|n','Use this to eat soup.'], ['smooth','s|m|oo|th','The opposite of rough.'],
 ['storm','s|t|or|m','Wild weather with strong wind and rain.'], ['sport','s|p|or|t','Football, tennis and cricket are each a type of this.'],
 ['brush','b|r|u|sh','Use this to tidy your hair.'], ['scrunch','s|c|r|u|n|ch','Squeeze paper into a ball.'],
 ['crisp','c|r|i|s|p','A thin, crunchy potato snack.'], ['stamp','s|t|a|m|p','Stick this on an envelope before posting it.'],
 ['twist','t|w|i|s|t','Turn something round, like a lid.'], ['chimp','ch|i|m|p','A short name for a chimpanzee.'],
 ['paint','p|ai|n|t','Use this with a brush to colour a wall.'], ['snail','s|n|ai|l','A slow animal with a shell on its back.'],
 ['chain','ch|ai|n','Metal links joined together.'], ['point','p|oi|n|t','Use your finger to show where something is.'],
 ['joint','j|oi|n|t','A place where two bones meet.'], ['crown','c|r|ow|n','A king might wear this on his head.'],
 ['brown','b|r|ow|n','The colour of chocolate.'], ['clown','c|l|ow|n','A circus performer who tries to make people laugh.'],
 ['start','s|t|ar|t','The opposite of finish.'], ['sharp','sh|ar|p','A well-pointed pencil is this.'],
 ['shelf','sh|e|l|f','A flat board for holding books.'], ['bench','b|e|n|ch','A long seat in a park.'],
 ['chest','ch|e|s|t','The part of your body with your ribs inside.'], ['lunch','l|u|n|ch','The meal in the middle of the day.'],
 ['fresh','f|r|e|sh','Bread just out of the oven is this.'], ['swing','s|w|i|ng','A hanging seat that moves backwards and forwards.'],
 ['think','th|i|n|k','Use your brain to work something out.'], ['thank','th|a|n|k','Do this when someone helps you.'],
 ['cliff','c|l|i|ff','A very steep rock face beside the sea.'], ['queen','qu|ee|n','A woman who rules a kingdom.']
 ]
};
const WORDS = Object.values(WORD_SETS).flat().map(([word,parts,clue])=>[word,parts.split('|'),clue]);
const SENTENCES = [
 ['I put my shoes on my ___.','feet',['hands','ears']],
 ['The train stopped at the ___.','station',['kitchen','garden']],
 ['We use a ___ to eat soup.','spoon',['fork','plate']],
 ['The ___ blew the leaves off the tree.','wind',['sand','rainbow']],
 ['I wore my coat ___ it was cold.','because',['between','under']],
 ['The dog wagged ___ tail.','its',['our','your']],
 ['There ___ three apples in the bowl.','are',['is','am']],
 ['Yesterday we ___ to the park.','went',['go','going']],
 ['The opposite of empty is ___.','full',['small','wide']],
 ['I can hear with my ___.','ears',['eyes','nose']],
 ['The ice melted in the warm ___.','sun',['snow','freezer']],
 ['Please ___ the door quietly.','close',['climb','drink']],
 ['The baby was tired, so she fell ___.','asleep',['awake','hungry']],
 ['I brushed my ___ before bed.','teeth',['shoes','knees']],
 ['We need an umbrella when it is ___.','raining',['sunny','dry']],
 ['A ___ has pages and a cover.','book',['ball','coat']],
 ['The bird built a ___ in the tree.','nest',['pond','road']],
 ['The opposite of noisy is ___.','quiet',['loud','busy']],
 ['I was thirsty, so I had a ___.','drink',['nap','jump']],
 ['She ___ a picture with her crayons.','drew',['threw','flew']],
 ['We ___ our hands before eating.','wash',['watch','wish']],
 ['The rabbit has long ___.','ears',['wings','fins']],
 ['The boat sailed across the ___.','lake',['field','road']],
 ['I looked both ways ___ crossing the road.','before',['during','through']],
 ['The opposite of remember is ___.','forget',['find','follow']],
 ['The ball rolled ___ the table, so I bent down to get it.','under',['over','above']],
 ['A person who makes bread is a ___.','baker',['driver','singer']],
 ['My socks are wet. I need a ___ pair.','dry',['dirty','damp']],
 ['The dog is bigger ___ the mouse.','than',['then','that']],
 ['We ___ football every Saturday.','play',['plays','playing']],
 ['He ___ his bag to school yesterday.','took',['take','taking']],
 ['There are seven days in a ___.','week',['month','year']],
 ['The opposite of difficult is ___.','easy',['hard','tricky']],
 ['The ___ keeps our food cold.','fridge',['oven','kettle']],
 ['I tied my ___ before running.','laces',['fingers','hairbrush']],
 ['A triangle has three ___.','sides',['circles','squares']],
 ['The children ___ playing outside now.','are',['was','is']],
 ['We ___ a lovely time at the beach yesterday.','had',['have','has']],
 ['Please put the books back on the ___.','shelf',['ceiling','window']],
 ['I could not reach it because it was too ___.','high',['low','short']]
];
